name: CI (uv)

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ "**" ]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      # Install uv and set the Python version for this matrix axis.
      - name: Set up uv + Python ${{ matrix.python-version }}
        uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ matrix.python-version }}
          enable-cache: true  # persist uv's cache between runs

      # If you have a uv.lock committed, keep installs reproducible.
      - name: Sync (install) project with uv
        run: |
          if [ -f uv.lock ]; then
            uv sync --locked --all-extras --dev
          else
            # First run (no lock yet) — resolve and create one for future runs
            uv sync --all-extras --dev
          fi

      - name: Run tests
        run: uv run pytest -q
